from ReinventQC.reinvent_scoring.scoring.diversity_filters.curriculum_learning.diversity_filter_memory import DiversityFilterMemory
from ReinventQC.reinvent_scoring.scoring.diversity_filters.curriculum_learning.diversity_filter_parameters import \
    DiversityFilterParameters